version: '3.3'

services:

  timpi:
    build: ./container
    container_name: timpi
    image: timpi

  collector:
    image: timpi:latest
    container_name: collector
    hostname: collector
    restart: always

    volumes:
      - ./src:/root/timpi
    entrypoint: ["/root/timpi/TimpiCollector"]

  collector-ui:
    image: timpi:latest
    container_name: collector-ui
    hostname: collector-ui
    restart: always

    ports:
      - "5015:5015"

    volumes:
      - ./src:/root/timpi
    entrypoint: ["/root/timpi/TimpiUI"]

  guardian:
    image: timpiltd/timpi-guardian
    container_name: guardian
    hostname: guardian
    restart: always
    ports:
      - "8983:8983"
      - "4005:4005"
    volumes:
      - ./data/guardian:/var/solr
    environment:
      - SOLR_PORT=8983
      - GUARDIAN_PORT=4005
      - SOLR_HOST=$SOLR_HOST
      - GUID=$GUID